apiVersion: v1
kind: Service
metadata:
  labels:
    run: checkurl
  name: checkurl
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: checkurl
  sessionAffinity: None
  type: NodePort

